### ISSUE TITLE
Include more <a>'s in the button code snippet examples.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/design-system#260]
As a design system user looking to see if i could use `<a>`'s for buttons, it took me a long time to figure out if it was OK. I looked at code snippets first, which are almost all `<button>`'s (except for "Big buttons, Primary". I still wasn't sure if it was OK to use it for other variants, until i read the help text at the bottom.  Including more `<a>`'s in the code snippets for other variants would be helpful.

**Comment by jaredcunha-usds** [comment]
Issue moved to [department-of-veterans-affairs/vets-design-system-documentation #28](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/28) via [**ZenHub**](https://www.zenhub.com/)
